mutation mutateBalita(
	$_key: String!
	$name: String!
	$gakin: String
	$jk: String!
	$tl: String!
	$ortu: String
	$rt: String
	$rw: String
	$posy: String!
	$inactive: Boolean
) {
	mutateBalita(
		_key: $_key
		name: $name
		gakin: $gakin
		jk: $jk
		tl: $tl
		ortu: $ortu
		rt: $rt
		rw: $rw
		posy: $posy
		inactive: $inactive
	) {
		_key
		name
		jk
		gakin
		tl
		ortu
		rt
		rw
		posy
		inactive
		penimbangan {
			_key
			tgl
			bb
			tb
		}
	}
}
